[package]
name = "webdev"
version = "0.1.0"
authors = ["mark.junge <mark.oliver@hotmail.de>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
rocket_contrib="*"
serde="*"
serde_derive="*"
serde_json="*"